### ISSUE TITLE
UI for Admin Dashboard

### ISSUE THREAD

**Issue by rumansaleem** [csdu/sankalan-portal#10]
Currently admin dashboard has no interface. A clean UI is needed for admin's dashboard to access all administrative features. Here are some of the highlights of the UI required:

- [x] Dashboard Layout with a clean sidebar, Sidebar contains links to manage certain resources.
- [x] List all participations & also filter them by event, presented in a clean table with suitable action buttons for each row. A Filter dropdown to list all events which can be filtered
- [x] A page for all Events & ability to begin or end event and a link to view all team participations and view all quizzes in that event.

This list is not **final**.

**Comment by vikashprajapati** [comment]
I would like to work on this.

**Comment by rumansaleem** [comment]
Alright then, first try to build the dashboard layout. Once layout is done, submit a PR with preview image.
