### ISSUE TITLE
Normal user's events page bug

### ISSUE THREAD

**Issue by yuvrajsab** [csdu/sankalan-portal#29]
when i visit events page as a normal user i encountered this bug. There is a method "canBeWithdrawn" which is missing in "Event" Model
![Screenshot from 2019-09-20 20-57-20](https://user-images.githubusercontent.com/27115069/65339464-d346b480-dbe9-11e9-85cb-b26d8a2f5595.png)

**Comment by rumansaleem** [comment]
Okay, I stripped that method. It was also used in user's dashboard. I replaced it with some code. Please refer to it and make a PR for this.

**Comment by rumansaleem** [comment]
closed by #30
