### ISSUE TITLE
Consider an upgrade to Laravel 8.x

### ISSUE THREAD

**Issue by rumansaleem** [csdu/sankalan-portal#45]
Current Laravel Version: 6.0

#### Upgrade Steps
- [ ] 6.0 -> 7.x - [Upgrade Guide](https://laravel.com/docs/7.x/upgrade)
- [ ] 7.x -> 8.0 - [Upgrade Guide](https://laravel.com/docs/8.x/upgrade)

**Comment by yuvrajsab** [comment]
Laravel v6 is **LTS** release, i don't think it's worth upgrading to v8 unless we've a specific reason to do so.

**Comment by rumansaleem** [comment]
I'm also not sure about, how much time it's gonna take to upgrade one LTS release to next LTS release. 

I see no point of waiting for an LTS release to do the upgrade. I assume it will also open opportunities for some decent refactor. It's just about maintaining and keep updating so, that you don't fall into "let's re-write the whole thing from scratch, it's legacy" trap.

**Comment by yuvrajsab** [comment]
closing for now.
