### ISSUE TITLE
Error on the give extra time page

### ISSUE THREAD

**Issue by rumansaleem** [csdu/sankalan-portal#51]
**STR**
- Seed Database
- Login as  a user participate in an event.
- Login as admin start that event and its quiz. (copy the token for quiz).
- As normal user attempt the quiz (using the copied token).
- As admin, goto QuizParticipation table, for each participation there is an action `Give Extra Time`, Click there.

**Current Behavior:** - Error page (see screenshot). 
**Expected behavior** - A form should be displayed with the inputs for time.

![image](https://user-images.githubusercontent.com/25204498/109422249-c47c4800-7a00-11eb-9391-600020cedee9.png)

**Comment by rumansaleem** [comment]
This is due to variable case sensitivity. (older versions of php are case-insensitive for identifiers)

**Comment by yuvrajsab** [comment]
Working fine on my system with php v7.4.
